name: Build Flutter APK

on:
  push:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Unzip Project
      run: |
        if [ -f "match_master.zip" ]; then
          unzip match_master.zip -d ./
        else
          unzip *.zip -d ./
        fi

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'

    # خطوة ذكية جداً تبحث عن ملف pubspec وتدخل لمكانه تلقائياً
    - name: Find Project Root and Install Dependencies
      run: |
        PUBSPEC_PATH=$(find . -name "pubspec.yaml" -print -quit)
        if [ -z "$PUBSPEC_PATH" ]; then
          echo "Error: pubspec.yaml not found anywhere!" && exit 1
        fi
        PROJECT_ROOT=$(dirname "$PUBSPEC_PATH")
        echo "PROJECT_PATH=$PROJECT_ROOT" >> $GITHUB_ENV
        cd $PROJECT_ROOT
        flutter pub get

    - name: Build APK
      run: |
        cd ${{ env.PROJECT_PATH }}
        flutter build apk --debug

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Candy_Crush_APK
        path: "**/build/app/outputs/flutter-apk/app-debug.apk"
